name: 'Setup Python and Poetry.'
description: 'Set up Python, install Poetry, cache dependencies, and install them with Poetry.'

inputs:
  python-version:
    description: 'Version of Python to use.'
    required: true
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: Checkout LFS objects
      shell: bash
      run: git lfs checkout

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Cache python dependencies
      uses: actions/cache@v3
      id: poetry-cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: |
        echo "::set-output name=version::$(poetry show playwright | grep "version" | awk '{print $3}')"

    - name: Cache playwright dependencies
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright/
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

    - name: Ensure python poetry installed
      shell: bash
      run: |
        echo "playwright version: ${{ steps.playwright-version.outputs.version }}"
        python --version
        poetry --version

    - name: Install dependencies with Poetry
      shell: bash
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      run: |
        mkdir ./dist && touch ./dist/README.md
        poetry install --no-interaction --without dev-e2e-windows

    - name: Install playwright dependencies with Poetry
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: poetry run playwright install chromium --with-deps