name: 'Setup Python and Poetry.'
description: 'Set up Python, install Poetry, cache dependencies, and install them with Poetry.'

runs:
  using: 'composite'
  steps:
    - name: Checkout LFS objects
      shell: bash
      run: git lfs checkout

    - name: Ensure python, poetry and playwright installed
      shell: bash
      run: |
        python --version
        poetry --version
        poetry run playwright -V    

    - name: Install dependencies with Poetry
      shell: bash
      run: |
        mkdir ./dist && touch ./dist/README.md
        poetry install --no-interaction

    - name: Install playwright dependencies with Poetry
      shell: bash
      run: |
        poetry run playwright install chromium --with-deps