name: Python Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    runs-on: windows-2022 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/windows
        with:
          python-version: '3.11'

      - name: Run tests with pytest
        shell: bash
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
        run: |
          poetry run pytest -vv --cov=pybas_automation --cov-report=html tests/
