name: Python Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    runs-on: windows-2022 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/windows
        with:
          python-version: '3.11'

      - name: Run tests with pytest
        shell: bash
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
        run: |
          mkdir -p ./coverage/lcov/functional
          poetry run pytest -vv --cov=pybas_automation --cov-report=lcov:coverage/lcov/functional/coverage.lcov tests/functional

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # https://github.com/codecov/codecov-action#arguments
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: tests_functional
          files: coverage/lcov/functional/coverage.lcov
          fail_ci_if_error: false