name: Windows CI
run-name: Windows CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  windows_test:
    runs-on: self-hosted
    #runs-on: windows-2022 # https://github.com/actions/runner-images#available-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Prepare
        uses: ./.github/actions/windows

      - name: Run tests with pytest
        shell: bash
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
          BRIGHTDATA_USERNAME: ${{ secrets.BRIGHTDATA_USERNAME }}
          BRIGHTDATA_PASSWORD: ${{ secrets.BRIGHTDATA_PASSWORD }}
        run: |
          mkdir -p ./coverage/lcov/
          poetry run pytest -vv --cov=pybas_automation --cov-report=lcov:coverage/lcov/coverage.lcov tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # https://github.com/codecov/codecov-action#arguments
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: tests_functional_e2e
          files: coverage/lcov/coverage.lcov
          fail_ci_if_error: false


  windows_poetry_build:
    needs: [ windows_test ]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python and Poetry
        uses: ./.github/actions/windows

      - name: Lint with mypy and flake8
        run: |
          poetry check
          poetry run python scripts/update_readme_links.py
          poetry build
