name: Python CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images#available-images

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies with Poetry
        run: |
          mkdir ./dist && touch ./dist/README.md
          poetry install --no-interaction --with dev,cmd,cmd-dev,docs
          poetry run playwright install chromium --with-deps

  test:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies with Poetry
        run: |
          mkdir ./dist && touch ./dist/README.md
          poetry install --no-interaction --with dev,cmd,cmd-dev,docs
          poetry run playwright install chromium --with-deps

      - name: Run tests with pytest
        env:
          FINGERPRINT_KEY: ${{ secrets.FINGERPRINT_KEY }}
        run: poetry run pytest -vv tests/
